[docusaurus]
url = "https://avafe.me"
tagline = "A modern, customizable hotbar for Roblox"
favicon = "/img/favicon.svg"

[home]
enabled = true

[[home.features]]
title = "Easy to Use"
description = "Getting started with NeoHotbar is easy, and customization is too."

[[home.features]]
title = "Customization"
description = "NeoHotbar features full GUI overriding, custom buttons and more. Make your hotbar for you."

[[home.features]]
title = "Feature Parity"
description = "NeoHotbar utilizes Tool objects and all of its features, just like the default Roblox hotbar."

[navbar]
# hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2023 Avafe. Built with Moonwave and Docusaurus"

# [[footer.docs]]
# title = "Docs"

# [[footer.docs.items]]
# label = "Getting Started"
# href = "https://avafe.me/NeoHotbar/docs/intro"
