name: Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0

    - name: Lint
      run: |
        selene ./src